# action.yml
name: ZIP-UNZIP-ACTION
author: Christopher Queen
description: a cURL CLI
inputs:
  args:  # id of input
    description: 'zip or unzip followed by zipFile and zipFolder arguments'
    required: true
    default: 'zip'
outputs:
  outputPath: # id of output
    description: 'Output path of zip or unzip'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
branding:
  icon: 'command'
  color: 'gray-dark'